config/routes.rb
Rails.application.routes.draw do
  get 'locationmap/show'

  resources :addonmaps
root to: "addonmaps#index"
  

end

app/models/addonmap.rb
class Addonmap < ActiveRecord::Base
	  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/addonmaps_controller.rb
class AddonmapsController < ApplicationController
  before_action :set_addonmap, only: [:show, :edit, :update, :destroy]

  # GET /addonmaps
  # GET /addonmaps.json
  def index
    @addonmaps = Addonmap.all
  end

  # GET /addonmaps/1
  # GET /addonmaps/1.json
  def show
  end

  # GET /addonmaps/new
  def new
    @addonmap = Addonmap.new
  end

  # GET /addonmaps/1/edit
  def edit
  end

  # POST /addonmaps
  # POST /addonmaps.json
  def create
    @addonmap = Addonmap.new(addonmap_params)

    respond_to do |format|
      if @addonmap.save
        format.html { redirect_to @addonmap, notice: 'Addonmap was successfully created.' }
        format.json { render :show, status: :created, location: @addonmap }
      else
        format.html { render :new }
        format.json { render json: @addonmap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addonmaps/1
  # PATCH/PUT /addonmaps/1.json
  def update
    respond_to do |format|
      if @addonmap.update(addonmap_params)
        format.html { redirect_to @addonmap, notice: 'Addonmap was successfully updated.' }
        format.json { render :show, status: :ok, location: @addonmap }
      else
        format.html { render :edit }
        format.json { render json: @addonmap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addonmaps/1
  # DELETE /addonmaps/1.json
  def destroy
    @addonmap.destroy
    respond_to do |format|
      format.html { redirect_to addonmaps_url, notice: 'Addonmap was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_addonmap
      @addonmap = Addonmap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def addonmap_params
      params.require(:addonmap).permit(:city_name,:latitude, :longitude, :name,:avatar)
  
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locationmap_controller.rb
class LocationmapController < ApplicationController
  def show
  	@locations = Addonmap.all
  end
end

app/helpers/addonmaps_helper.rb
module AddonmapsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locationmap_helper.rb
module LocationmapHelper
end

app/views/addonmaps/_form.html.erb
<%= form_for(@addonmap,:html=>{:name=>"f",:onsubmit=>"getLocation(event);"})  do |f| %>
  <% if @addonmap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@addonmap.errors.count, "error") %> prohibited this addonmap from being saved:</h2>

      <ul>
      <% @addonmap.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!-- get latitude and longitude -->
  <%= f.hidden_field  :latitude %>
   <%= f.hidden_field  :longitude %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
    <div class="field">
    <%= f.label :city_name %><br>
    <%= f.text_field :city_name %>
  </div>
    <div>
  Image upload: <%= f.file_field :avatar  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addonmaps/edit.html.erb
<h1>Editing Addonmap</h1>

<%= render 'form' %>

<%= link_to 'Show', @addonmap %> |
<%= link_to 'Back', addonmaps_path %>

app/views/addonmaps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Addonmaps</h1>

<table>
  <thead>
    <tr>
      <th>place</th>
      <th>specie name</th>
      <th>Image</th>
  
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addonmaps.each do |addonmap| %>
      <tr>
        <td><%= addonmap.city_name %></td>
        <td><%= addonmap.name %></td>
        <td><%= image_tag addonmap.avatar.url(:thumb) %>  <td> 
        <td><%= link_to 'Show', addonmap %></td>
        <td><%= link_to 'Edit', edit_addonmap_path(addonmap) %></td>
        <td><%= link_to 'Destroy', addonmap, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Addonmap', new_addonmap_path %>
<br>
<%= link_to "See all popular sightings", locationmap_show_path, class: "btn btn-link"  %>

app/views/addonmaps/new.html.erb
<h1>New Addonmap</h1>

<%= render 'form' %>

<%= link_to 'Back', addonmaps_path %>

app/views/addonmaps/show.html.erb
<p id="notice"><%= notice %></p>

<div>
<%= image_tag @addonmap.avatar.url(:thumb) %>
</div>

<p>
  <strong>Name:</strong>
  <%= @addonmap.name %>
</p>
<p>
  <strong>Place:</strong>
  <%= @addonmap.city_name %>
</p>
<%= link_to 'Edit', edit_addonmap_path(@addonmap) %> |
<%= link_to 'Back', addonmaps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddToMap</title>
   <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locationmap/show.html.erb
<!-- ++++++++++++++++++++++++++++++ -->
<body >


      <h3 class="center-align">Location of all sightings</h3>
		
	<div style="display:none">
  		<%= image_tag("missing.jpg",:id => "missing") %>
	</div>
	<div id="map1" style="border:1px solid red; height:500px;"></div>
	  <script type="text/javascript">
		  var reports = new Array();
		  var report;
		  var tmp;
		  <% count = 0
		  @locations.each do |report|  %>
		  report = new Array();
		  report["species"] = "<%= report.name  %>";
		  report["lat"] = <%= report.latitude %>;
		  report["lng"] = <%= report.longitude %>;
		  tmp= "<%= report.avatar.url(:thumb) %>";
		  if(tmp=="missing.jpg")
		  {
		  	//console.log("sd");
		  	tmp= document.getElementById("missing").src;
		  }
		  tmp= document.getElementById("missing").src;
		  //console.log(tmp);
		  report["image"] = tmp;
		  reports[<%= count %>] = report;
		  <% count +=1 end %>
		  //load_list(reports);

	    var map = new google.maps.Map(document.getElementById('map1'), {
	      zoom: 10,
	      center: new google.maps.LatLng(15.408186, 74.194498),
	      mapTypeId: google.maps.MapTypeId.ROADMAP
	    });

	    var infowindow = new google.maps.InfoWindow();
		
	    var marker, i;
	    //console.log( reports.length);
	    for (i = 0; i < reports.length; i++) {  
	     
		  marker = new google.maps.Marker({
	        position: new google.maps.LatLng(reports[i]["lat"], reports[i]["lng"]),
	        map: map,
			icon:reports[i]["image"],
	            
			
	      });

	      google.maps.event.addListener(marker, 'click', (function(marker, i) {
	        return function() {
	          infowindow.setContent(reports[i]["species"]);
	          infowindow.open(map, marker);
	        }
	      })(marker, i));
	    }
	  </script>


<h3 class="center-align">Popular location of species</h3>
  	<div id="map2" style="border:1px solid red; height:500px;"></div>
	<div style="display:none">

	  <%= image_tag("kc.png",:id => "kc") %>
	  <%= image_tag("cobra.png",:id => "cobra") %>
	  <%= image_tag("RV.png",:id => "RV") %>
	  <%= image_tag("krait.png",:id => "krait") %>
	  <%= image_tag("saw.png",:id => "saw") %>
	</div>
	  <script type="text/javascript">

	  onmap();
	  function onmap(){

	    var locations = [
	    ['King Cobra', 15.609679, 74.06487, document.getElementById("kc").src],//sattari
		  ['Cobra', 15.549053, 74.071131, document.getElementById("cobra").src],
		  ['Russells Viper', 15.575292, 73.990905, document.getElementById("RV").src],
		  
	    ['Russells Viper', 15.28297, 74.020964,document.getElementById("RV").src], //margao
		  ['Cobra', 15.285645, 74.003901,document.getElementById("cobra").src],
	    ['Common Krait', 15.271645, 73.998226,document.getElementById("krait").src],
		 
		  ['Russells Viper', 15.398226, 74.026725,document.getElementById("RV").src], //ponda
		  ['Cobra', 15.386098, 74.030572,document.getElementById("cobra").src],
	    ['Common Krait', 15.411068, 74.00334,document.getElementById("krait").src],
	    ['Saw Scaled Viper', 15.384794, 73.996817,document.getElementById("saw").src],
		  
		  ['King Cobra', 15.117129, 74.205804,document.getElementById("kc").src], //netravali
		  ['Cobra', 15.10672, 74.160631,document.getElementById("cobra").src],
	    ['Common Krait', 15.131056, 74.150373,document.getElementById("krait").src],
	    ['Saw Scaled Viper', 15.112347, 74.125771,document.getElementById("saw").src]
	    ];

	    var map = new google.maps.Map(document.getElementById('map2'), {
	      zoom: 10,
	      center: new google.maps.LatLng(15.408186, 74.194498),
	      mapTypeId: google.maps.MapTypeId.ROADMAP
	    });

	    var infowindow = new google.maps.InfoWindow();
		
	    var marker, i;

	    for (i = 0; i < locations.length; i++) {  
	      var image = 'cobra.jpg';
		  marker = new google.maps.Marker({
	        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
	        map: map,
			icon:locations[i][3],
	            
			
	      });

	      google.maps.event.addListener(marker, 'click', (function(marker, i) {
	        return function() {
	          infowindow.setContent(locations[i][0]);
	          infowindow.open(map, marker);
	        }
	      })(marker, i));
	    }
	}
	  </script>


</body>